from enum import IntEnum


TICK_PERIOD = 0.05
PANE_PADDING = 2
PANE_HEIGHT = 2 * PANE_PADDING + 6
CELL_SIZE = 16
WIDTH_IN_CELL_COUNT = 16
HEIGHT_IN_CELL_COUNT = 16
TRANSPARENT_COLOR = 0

MAX_HUNGER_LIMIT = 100
INITIAL_FOOD_SATIETY_AMOUNT = 100
INITIAL_FOOD_TAIL_AMOUNT = 2


class GameState(IntEnum):
    START = 0
    PAUSED = 1
    PLAYING = 2
    OVER = 3
    RESTARTED = 4


class Direction(IntEnum):
    RIGHT = 0
    DOWN = 1
    LEFT = 2
    UP = 3


class FoodType(IntEnum):
    REGULAR = 0
    DEAL = 1
